Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\piccipherdraft3\settings.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloaderBad Request: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Request Headers: {'Content-Length': '1242227', 'Content-Type': 'multipart/form-data; boundary=bdaddb50-be2a-4630-8558-a62ae9604ba8', 'User-Agent': 'Mozilla/5.0 (Windows NT; Windows NT 10.0; en-IN) WindowsPowerShell/5.1.22621.1778', 'Host': '127.0.0.1:8000', 'Expect': '100-continue', 'Connection': 'Keep-Alive'}
No image provided in the request.
Bad Request: /api/upload-image/
Request Headers: {'Content-Length': '1242227', 'Content-Type': 'multipart/form-data; boundary=bdaddb50-be2a-4630-8558-a62ae9604ba8', 'User-Agent': 'Mozilla/5.0 (Windows NT; Windows NT 10.0; en-IN) WindowsPowerShell/5.1.22621.1778', 'Host': '127.0.0.1:8000', 'Expect': '100-continue'}
No image provided in the request.
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py", line 24, in post
    self.store_data_in_mongodb(uploaded_image, ocr_text)
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py", line 37, in store_data_in_mongodb
    "image_url": uploaded_image.url,
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'InMemoryUploadedFile' object has no attribute 'url'
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py", line 24, in post
    self.store_data_in_mongodb(uploaded_image, ocr_text)
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py", line 37, in store_data_in_mongodb
    "image_url": uploaded_image.url,
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'InMemoryUploadedFile' object has no attribute 'url'
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py", line 21, in post
    self.store_data_in_mongodb(uploaded_image, ocr_text)
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py", line 34, in store_data_in_mongodb
    "image_url": uploaded_image.url,
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'InMemoryUploadedFile' object has no attribute 'url'
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py", line 23, in post
    self.store_data_in_mongodb(uploaded_image, ocr_text)
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py", line 35, in store_data_in_mongodb
    with open(save_path, 'wb') as destination:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Shibu Punneth Varkey\\OneDrive\\Documents\\VS Code Codes\\Python\\Django\\piccipherdraft3\\media\\uploads\\ocr.jpg'
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
STREAM b'IHDR' 16 13
STREAM b'tEXt' 41 25
STREAM b'iTXt' 78 786
STREAM b'IDAT' 876 109002
Method Not Allowed: /api/upload-image/
Method Not Allowed: /api/upload-image/
STREAM b'IHDR' 16 13
STREAM b'IDAT' 41 8192
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\apps.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\apps.py changed, reloading.
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Python\Django\piccipherdraft3\api_3\apps.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Method Not Allowed: /api/upload-image/
STREAM b'IHDR' 16 13
STREAM b'tEXt' 41 25
STREAM b'iTXt' 78 786
STREAM b'IDAT' 876 109002
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
tag: YResolution (283) - type: rational (5) Tag Location: 22 - Data Location: 146 - value: b'H\x00\x00\x00\x01\x00\x00\x00'
tag: XResolution (282) - type: rational (5) Tag Location: 34 - Data Location: 154 - value: b'H\x00\x00\x00\x01\x00\x00\x00'
tag: ImageWidth (256) - type: long (4) - value: b'\x80\x07\x00\x00'
tag: Software (305) - type: string (2) Tag Location: 58 - Data Location: 162 - value: b'MediaTek Camera Application\x00\x00\x00\x00\x00'
tag: ImageLength (257) - type: long (4) - value: b'@\x10\x00\x00'
tag: ImageDescription (270) - type: string (2) Tag Location: 82 - Data Location: 194 - value: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
tag: YCbCrPositioning (531) - type: short (3) - value: b'\x02\x00'
tag: ExifIFD (34665) - type: long (4) - value: b'\xe2\x00\x00\x00'
tag: ResolutionUnit (296) - type: short (3) - value: b'\x02\x00'
tag: Orientation (274) - type: short (3) - value: b'\x00\x00'
tag: GPSInfoIFD (34853) - type: long (4) - value: b'\xa0\x01\x00\x00'
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
STREAM b'IHDR' 16 13
STREAM b'gAMA' 41 4
STREAM b'cHRM' 57 32
STREAM b'bKGD' 101 2
b'bKGD' 101 2 (unknown)
STREAM b'tIME' 115 7
b'tIME' 115 7 (unknown)
STREAM b'IDAT' 134 16212
STREAM b'tEXt' 16358 62
STREAM b'tEXt' 16432 23
STREAM b'tEXt' 16467 37
STREAM b'tEXt' 16516 37
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Method Not Allowed: /api/upload-image/
Method Not Allowed: /api/upload-image/
Method Not Allowed: /api/upload-image/
Method Not Allowed: /api/upload-image/
tag: Orientation (274) - type: long (4) - value: b'\x01\x00\x00\x00'
tag: Software (305) - type: string (2) Tag Location: 34 - Data Location: 62 - value: b'Snapseed 2.0\x00'
tag: DateTime (306) - type: string (2) Tag Location: 46 - Data Location: 75 - value: b'2023:10:07 11:23:35\x00'
tag: ExifIFD (34665) - type: long (4) - value: b'_\x00\x00\x00'
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /api/upload-image/
Method Not Allowed: /api/upload-image/
Not Found: /api/get_items/
Method Not Allowed: /api/upload-image/
Bad Request: /api/upload-image/
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
tag: YResolution (283) - type: rational (5) Tag Location: 22 - Data Location: 146 - value: b'H\x00\x00\x00\x01\x00\x00\x00'
tag: XResolution (282) - type: rational (5) Tag Location: 34 - Data Location: 154 - value: b'H\x00\x00\x00\x01\x00\x00\x00'
tag: ImageWidth (256) - type: long (4) - value: b'\x80\x07\x00\x00'
tag: Software (305) - type: string (2) Tag Location: 58 - Data Location: 162 - value: b'MediaTek Camera Application\x00\x00\x00\x00\x00'
tag: ImageLength (257) - type: long (4) - value: b'@\x10\x00\x00'
tag: ImageDescription (270) - type: string (2) Tag Location: 82 - Data Location: 194 - value: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
tag: YCbCrPositioning (531) - type: short (3) - value: b'\x02\x00'
tag: ExifIFD (34665) - type: long (4) - value: b'\xe2\x00\x00\x00'
tag: ResolutionUnit (296) - type: short (3) - value: b'\x02\x00'
tag: Orientation (274) - type: short (3) - value: b'\x00\x00'
tag: GPSInfoIFD (34853) - type: long (4) - value: b'\xa0\x01\x00\x00'
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
Method Not Allowed: /api/upload-image/
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Unsupported Media Type: /api/upload-image/
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
Unsupported Media Type: /api/upload-image/
Unsupported Media Type: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
Unsupported Media Type: /api/upload-image/
Unsupported Media Type: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\forms.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/upload-image/
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Not Found: /api/upload-image/
Not Found: /api/upload-image/
Not Found: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py", line 47, in upload_image
    return render(request, 'upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: upload_image.html
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py", line 47, in upload_image
    return render(request, 'upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: upload_image.html
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Not Found: /api/api/upload-images
Method Not Allowed: /api/api/upload-image/
Method Not Allowed: /api/api/upload-image/
Method Not Allowed: /api/api/upload-image/
Bad Request: /api/api/upload-image/
Not Found: /api/upload-image/
Not Found: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py", line 47, in upload_image
    return render(request, 'upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: upload_image.html
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py", line 47, in upload_image
    return render(request, 'upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: upload_image.html
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Internal Server Error: /api/upload-image/
Traceback (most recent call last):
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py", line 47, in upload_image
    return render(request, 'upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shibu Punneth Varkey\.virtualenvs\Shibu_Punneth_Varkey-OTaJPIlG\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: upload_image.html
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Not Found: /api/upload-image/
Method Not Allowed: /api/api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /api/api/upload-image/
Method Not Allowed: /api/upload-image/
Method Not Allowed: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\api_3\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Method Not Allowed: /api/upload-image/
Bad Request: /api/upload-image/
C:\Users\Shibu Punneth Varkey\OneDrive\Documents\VS Code Codes\Piccipher\Django-branch\PicCipher-master\piccipherdraft3\settings.py changed, reloading.
